use FORMULARIO_110

--SECTION A
select CONTRIBUYENTE.DOCUMENTO_IDENTIDAD, LUGAR_EXPEDICION.LUGAR, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, DOMICILIO 
from CONTRIBUYENTE, LUGAR_EXPEDICION, FORMULARIO_110
where 
	CONTRIBUYENTE.DOCUMENTO_IDENTIDAD=FORMULARIO_110.DOCUMENTO_IDENTIDAD AND 
	CONTRIBUYENTE.ID_LUGAR = LUGAR_EXPEDICION.ID_LUGAR AND
	FORMULARIO_110.NUMERO_ORDEN = '1111' 

--SECTION B
select NUMERO_NIT, RAZON_SOCIAL, EMPLEADOR.DOMICILIO
from EMPLEADOR, CONTRIBUYENTE, FORMULARIO_110
where 
	FORMULARIO_110.DOCUMENTO_IDENTIDAD = CONTRIBUYENTE.DOCUMENTO_IDENTIDAD AND
	CONTRIBUYENTE.NUMERO_NIT_EMPLEADOR = EMPLEADOR.NUMERO_NIT AND
	FORMULARIO_110.NUMERO_ORDEN = '1111'


--SECTION C
select NUMERO_FACTURA, NIT, NUMERO_AUTORIZACION, FECHA, IMPORTE, CODIGO_CONTROL
from FACTURA
where 
	FACTURA.NUMERO_ORDEN_FORMULARIO = '1111'


-- SECTION D
select TOTAL_DETALLE, DETERMINACION_PAGO
from FORMULARIO_110
where 
	FORMULARIO_110.NUMERO_ORDEN = '1111'

go